
# Define a pet system
/gate/world/daughters/name            ecat
/gate/world/daughters/insert   	      cylinder
/gate/ecat/placement/setTranslation   0.0 0.0 0.0 cm
/gate/ecat/geometry/setRmax           22 cm
/gate/ecat/geometry/setRmin           20 cm
/gate/ecat/geometry/setHeight         5 cm
/gate/ecat/setMaterial                Air
/gate/ecat/vis/forceWireframe
/gate/ecat/vis/setColor               red

#	Block
/gate/ecat/daughters/name                     blockDetector
/gate/ecat/daughters/insert                   box
/gate/blockDetector/placement/setTranslation  21 0 0 cm
/gate/blockDetector/geometry/setXLength       1 cm
/gate/blockDetector/geometry/setYLength       4.8 cm # 12*4mm for crystal + 11*0.5 for gaps
/gate/blockDetector/geometry/setZLength       4.8 cm
/gate/blockDetector/setMaterial               Air
/gate/ecat/vis/forceWireframe
/gate/blockDetector/vis/setColor              green

#	Crystal
/gate/blockDetector/daughters/name             crystalUnit
/gate/blockDetector/daughters/insert           box
/gate/crystalUnit/placement/setTranslation     0.0 0.0 0.0 mm
/gate/crystalUnit/geometry/setXLength          10. mm
/gate/crystalUnit/geometry/setYLength          0.925 mm
/gate/crystalUnit/geometry/setZLength          0.925 mm
/gate/crystalUnit/setMaterial                  LYSO
/gate/crystalUnit/vis/setColor                 yellow
#/gate/crystalUnit/vis/setVisible              0


#Fix from here down for initial setup/protoype
# Repeat the block and the crystal
# Block: ring(x46) & linear(x4)
# Crystal: cubicArray(12x12)
/gate/blockDetector/repeaters/insert                  ring
/gate/blockDetector/ring/setRepeatNumber              2
/gate/blockDetector/ring/setFirstAngle                0 deg
/gate/blockDetector/ring/setAngularSpan               180 deg
/gate/blockDetector/ring/enableAutoRotation


/gate/crystalUnit/repeaters/insert                    cubicArray
/gate/crystalUnit/cubicArray/setRepeatNumberX         1
/gate/crystalUnit/cubicArray/setRepeatNumberY         48
/gate/crystalUnit/cubicArray/setRepeatNumberZ         48
/gate/crystalUnit/cubicArray/setRepeatVector          10.0 0.925 0.925 mm

# Attach the volumes to the system tree
/gate/systems/ecat/block/attach     blockDetector
/gate/systems/ecat/crystal/attach   crystalUnit

# Definition of the sensitive detector
/gate/crystalUnit/attachCrystalSD


# Verbosity
/gate/systems/ecat/describe

