
# Visualisation
/control/execute mac/visu.mac

# Verbosity
/control/execute mac/verbose.mac

# Geometry
/control/execute mac/world.mac
/control/execute mac/pet_head.mac 
#/control/execute mac/ecat_geometry.mac
#/control/execute mac/pet_digitizer.mac
/control/execute mac/trialCoincPetDigi.mac
#/control/execute mac/cylindrical_phantom.mac
# Physics
/control/execute mac/physics.mac

# Output
/control/execute mac/output.mac 

# Initialisation
/gate/run/initialize

# Source
#/control/execute mac/source_f18.mac
/control/execute mac/source_2gammas.mac
#/control/execute mac/pointsource_2gammas.mac

# Random
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

# Start acquisition
/gate/application/setTimeStart 0 s
/gate/application/setTimeSlice 100 s
/gate/application/setTimeStop  100 s
/gate/application/start
