
# Visualisation
/control/execute phytoPet/myVisu.mac

# Verbosity
/control/execute phytoPet/myVerbose.mac

# Geometry
/control/execute phytoPet/myWorld.mac
/control/execute phytoPet/rdg_geo.mac
#/control/execute phytoPet/ecat_geometry.mac
/control/execute phytoPet/myPet_digitizer.mac
#/control/execute phytoPet/myCylindrical_phantom.mac
# Physics
/control/execute phytoPet/myPhysics.mac

# Output
/control/execute phytoPet/myOutput.mac

# Initialisation
/gate/run/initialize

# Source
#/control/execute phytoPet/mySource_f18.mac
/control/execute phytoPet/mySource_2gammas.mac

# Random
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

# Start acquisition
/gate/application/setTimeStart 0 s
/gate/application/setTimeSlice 1500 s
/gate/application/setTimeStop  1500 s
/gate/application/start
