
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/RDGsetup_biased_resAng.txt
/gate/actor/stat/saveEveryNSeconds 50


# Define a root listmode file output

/gate/output/root/enable
/gate/output/root/setFileName             output/RDGsetup_biased_resAng

/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1
/gate/output/root/setRootNtupleFlag       1


/gate/phantom/attachPhantomSD
